### ISSUE TITLE
void

### ISSUE THREAD

**Issue by ghost** [revolution0x/society0x-wiki#1]

**Comment by JayWelsh** [comment]
The wiki is under construction and will be committed into this repo. Sorry for the delay.

**Comment by lazaridiscom** [comment]
Process: do not close issues immediately

Issue at hand: Remove this Repo. Once there is something to commit, create the repo

**Comment by JayWelsh** [comment]
I have added some code for the backbone of the wiki, excluding the initial wiki docs which are still under revision.

**Comment by lazaridiscom** [comment]
Just shred it for now. Far too much draft repos, and i get distracted.
